  INFO root [0x00003514] [2019-03-01 13:35:11,953] - 
  INFO root [0x00003514] [2019-03-01 13:35:11,953] - -----------------------------------------------------------------------------------------


  INFO root [0x00003514] [2019-03-01 13:35:11,973] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003514] [2019-03-01 13:35:11,973] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003514] [2019-03-01 13:35:11,973] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003514] [2019-03-01 13:35:12,018] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003514] [2019-03-01 13:35:12,019] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003514] [2019-03-01 13:35:12,021] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003514] [2019-03-01 13:35:12,021] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003514] [2019-03-01 13:35:12,023] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:14687 )
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:14687, SOMAXCONN=128.
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - server-configs:
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	gameUpdateHertz : 10
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	entryScriptFile : kbemain
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	internalTcpAddr : 192.168.0.148:14687
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003514] [2019-03-01 13:35:12,024] - 	componentID : 7001
  WARN root [0x00003514] [2019-03-01 13:35:12,354] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003514] [2019-03-01 13:35:12,418] - Components::findLogger: found logger, addr:192.168.0.148:14556
  INFO root [0x00003514] [2019-03-01 13:35:12,418] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003514] [2019-03-01 13:35:12,418] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003514] [2019-03-01 13:35:12,422] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 13584 ----
  INFO root [0x00003514] [2019-03-01 13:35:12,423] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003514] [2019-03-01 13:35:13,193] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003514] [2019-03-01 13:35:13,194] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003514] [2019-03-01 13:35:13,468] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003514] [2019-03-01 13:35:13,468] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003514] [2019-03-01 13:35:13,765] - loaded entity-script:Account(1).
 DEBUG root [0x00003514] [2019-03-01 13:35:13,766] - loaded entity-script:Halls(2).
 DEBUG root [0x00003514] [2019-03-01 13:35:13,766] - loaded entity-script:Room(3).
  INFO root [0x00003514] [2019-03-01 13:35:13,766] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003514] [2019-03-01 13:35:13,791] - TelnetServer server is running on port 40000
  INFO root [0x00003514] [2019-03-01 13:35:14,255] - ---- baseapp is running ----
 DEBUG root [0x00003514] [2019-03-01 13:35:14,257] - Components::process(): Request for the process of identity...
  WARN root [0x00003514] [2019-03-01 13:35:20,451] - Forwarding logs to logger[192.168.0.148:14556/0/0/0]...
 ERROR root [0x00003514] [2019-03-01 13:40:23,479] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003514] [2019-03-01 13:40:23,486] - The following logs sent to logger failed:
  WARN root [0x00003514] [2019-03-01 13:40:23,486] - ==> [2019-03-01 13:40:23 479] TCPPacketReceiver::processPendingEvents(192.168.0.148:14556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003514] [2019-03-01 13:40:23,486] - ==> [2019-03-01 13:40:23 481] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003514] [2019-03-01 13:40:23,522] - TCPPacketReceiver::processPendingEvents(192.168.0.148:14604): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003514] [2019-03-01 13:40:23,523] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003514] [2019-03-01 13:40:23,546] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003514] [2019-03-01 13:40:23,547] - onBaseAppShutDown: state=0
  INFO root [0x00003514] [2019-03-01 13:40:23,547] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003514] [2019-03-01 13:40:23,547] - onBaseAppShutDown: state=1
  INFO root [0x00003514] [2019-03-01 13:40:23,547] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003514] [2019-03-01 13:40:23,547] - onBaseAppShutDown: state=2
 ERROR root [0x00003514] [2019-03-01 13:40:23,600] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,602] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,603] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,604] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,604] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,605] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,606] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003514] [2019-03-01 13:40:23,606] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003514] [2019-03-01 13:40:23,607] - Halls::~Halls(): 1
 DEBUG root [0x00003514] [2019-03-01 13:40:23,607] - Account::~Account(): 2
 DEBUG root [0x00003514] [2019-03-01 13:40:23,607] - Account::~Account(): 4
 DEBUG root [0x00003514] [2019-03-01 13:40:23,607] - Room::~Room(): 3
 DEBUG root [0x00003514] [2019-03-01 13:40:23,607] - Account::~Account(): 5
 DEBUG root [0x00003514] [2019-03-01 13:40:23,608] - Account::~Account(): 7
 DEBUG root [0x00003514] [2019-03-01 13:40:23,608] - Room::~Room(): 6
  INFO root [0x00003514] [2019-03-01 13:40:23,621] - Script::uninstall(): is successfully!
 DEBUG root [0x00003514] [2019-03-01 13:40:23,621] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000017cc] [2019-03-01 14:44:01,571] - 
  INFO root [0x000017cc] [2019-03-01 14:44:01,571] - -----------------------------------------------------------------------------------------


  INFO root [0x000017cc] [2019-03-01 14:44:01,573] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x000017cc] [2019-03-01 14:44:01,573] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x000017cc] [2019-03-01 14:44:01,573] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x000017cc] [2019-03-01 14:44:01,581] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x000017cc] [2019-03-01 14:44:01,581] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:11437 )
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:11437, SOMAXCONN=128.
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - server-configs:
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	gameUpdateHertz : 10
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	entryScriptFile : kbemain
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	internalTcpAddr : 192.168.0.148:11437
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x000017cc] [2019-03-01 14:44:01,584] - 	componentID : 7001
  WARN root [0x000017cc] [2019-03-01 14:44:01,931] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x000017cc] [2019-03-01 14:44:02,125] - Components::findLogger: found logger, addr:192.168.0.148:11435
  INFO root [0x000017cc] [2019-03-01 14:44:02,130] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000017cc] [2019-03-01 14:44:02,130] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000017cc] [2019-03-01 14:44:02,133] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 6968 ----
  INFO root [0x000017cc] [2019-03-01 14:44:02,133] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x000017cc] [2019-03-01 14:44:02,138] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000017cc] [2019-03-01 14:44:02,138] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000017cc] [2019-03-01 14:44:02,314] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000017cc] [2019-03-01 14:44:02,314] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000017cc] [2019-03-01 14:44:02,417] - loaded entity-script:Account(1).
 DEBUG root [0x000017cc] [2019-03-01 14:44:02,417] - loaded entity-script:Halls(2).
 DEBUG root [0x000017cc] [2019-03-01 14:44:02,417] - loaded entity-script:Room(3).
  INFO root [0x000017cc] [2019-03-01 14:44:02,418] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000017cc] [2019-03-01 14:44:02,418] - TelnetServer server is running on port 40000
  INFO root [0x000017cc] [2019-03-01 14:44:02,758] - ---- baseapp is running ----
 DEBUG root [0x000017cc] [2019-03-01 14:44:02,759] - Components::process(): Request for the process of identity...
  WARN root [0x000017cc] [2019-03-01 14:44:08,939] - Forwarding logs to logger[192.168.0.148:11435/0/0/0]...
 ERROR root [0x000017cc] [2019-03-01 14:45:29,794] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000017cc] [2019-03-01 14:45:29,797] - The following logs sent to logger failed:
  WARN root [0x000017cc] [2019-03-01 14:45:29,797] - ==> [2019-03-01 14:45:29 795] TCPPacketReceiver::processPendingEvents(192.168.0.148:11435): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000017cc] [2019-03-01 14:45:29,798] - ==> [2019-03-01 14:45:29 795] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x000017cc] [2019-03-01 14:45:29,838] - TCPPacketReceiver::processPendingEvents(192.168.0.148:11431): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000017cc] [2019-03-01 14:45:29,838] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000017cc] [2019-03-01 14:45:29,844] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000017cc] [2019-03-01 14:45:29,847] - onBaseAppShutDown: state=0
  INFO root [0x000017cc] [2019-03-01 14:45:29,848] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000017cc] [2019-03-01 14:45:29,848] - onBaseAppShutDown: state=1
  INFO root [0x000017cc] [2019-03-01 14:45:29,848] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000017cc] [2019-03-01 14:45:29,848] - onBaseAppShutDown: state=2
 ERROR root [0x000017cc] [2019-03-01 14:45:29,863] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000017cc] [2019-03-01 14:45:29,864] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000017cc] [2019-03-01 14:45:29,865] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x000017cc] [2019-03-01 14:45:29,866] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000017cc] [2019-03-01 14:45:29,867] - Halls::~Halls(): 1
 DEBUG root [0x000017cc] [2019-03-01 14:45:29,867] - Account::~Account(): 2
 DEBUG root [0x000017cc] [2019-03-01 14:45:29,867] - Account::~Account(): 4
 DEBUG root [0x000017cc] [2019-03-01 14:45:29,867] - Room::~Room(): 3
  INFO root [0x000017cc] [2019-03-01 14:45:29,875] - Script::uninstall(): is successfully!
 DEBUG root [0x000017cc] [2019-03-01 14:45:29,876] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000650] [2019-03-01 15:22:24,687] - 
  INFO root [0x00000650] [2019-03-01 15:22:24,692] - -----------------------------------------------------------------------------------------


  INFO root [0x00000650] [2019-03-01 15:22:24,695] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00000650] [2019-03-01 15:22:24,695] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00000650] [2019-03-01 15:22:24,696] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00000650] [2019-03-01 15:22:24,700] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00000650] [2019-03-01 15:22:24,700] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00000650] [2019-03-01 15:22:24,704] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00000650] [2019-03-01 15:22:24,704] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00000650] [2019-03-01 15:22:24,706] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:3499 )
  INFO root [0x00000650] [2019-03-01 15:22:24,706] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:3499, SOMAXCONN=128.
  INFO root [0x00000650] [2019-03-01 15:22:24,706] - server-configs:
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	gameUpdateHertz : 10
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	entryScriptFile : kbemain
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	internalTcpAddr : 192.168.0.148:3499
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00000650] [2019-03-01 15:22:24,707] - 	componentID : 7001
  WARN root [0x00000650] [2019-03-01 15:22:25,018] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00000650] [2019-03-01 15:22:25,246] - Components::findLogger: found logger, addr:192.168.0.148:3493
  INFO root [0x00000650] [2019-03-01 15:22:25,246] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00000650] [2019-03-01 15:22:25,246] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000650] [2019-03-01 15:22:25,252] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 4144 ----
  INFO root [0x00000650] [2019-03-01 15:22:25,253] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00000650] [2019-03-01 15:22:25,253] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000650] [2019-03-01 15:22:25,253] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00000650] [2019-03-01 15:22:25,434] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00000650] [2019-03-01 15:22:25,435] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000650] [2019-03-01 15:22:25,562] - loaded entity-script:Account(1).
 DEBUG root [0x00000650] [2019-03-01 15:22:25,563] - loaded entity-script:Halls(2).
 DEBUG root [0x00000650] [2019-03-01 15:22:25,564] - loaded entity-script:Room(3).
  INFO root [0x00000650] [2019-03-01 15:22:25,564] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000650] [2019-03-01 15:22:25,564] - TelnetServer server is running on port 40000
  INFO root [0x00000650] [2019-03-01 15:22:25,950] - ---- baseapp is running ----
 DEBUG root [0x00000650] [2019-03-01 15:22:25,951] - Components::process(): Request for the process of identity...
  WARN root [0x00000650] [2019-03-01 15:22:32,090] - Forwarding logs to logger[192.168.0.148:3493/0/0/0]...
 ERROR root [0x00000650] [2019-03-01 15:23:45,816] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00000650] [2019-03-01 15:23:45,820] - The following logs sent to logger failed:
  WARN root [0x00000650] [2019-03-01 15:23:45,820] - ==> [2019-03-01 15:23:45 816] TCPPacketReceiver::processPendingEvents(192.168.0.148:3493): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000650] [2019-03-01 15:23:45,821] - ==> [2019-03-01 15:23:45 817] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00000650] [2019-03-01 15:23:45,861] - TCPPacketReceiver::processPendingEvents(192.168.0.148:3496): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000650] [2019-03-01 15:23:45,862] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00000650] [2019-03-01 15:23:45,866] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00000650] [2019-03-01 15:23:45,869] - onBaseAppShutDown: state=0
  INFO root [0x00000650] [2019-03-01 15:23:45,870] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00000650] [2019-03-01 15:23:45,870] - onBaseAppShutDown: state=1
  INFO root [0x00000650] [2019-03-01 15:23:45,870] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00000650] [2019-03-01 15:23:45,870] - onBaseAppShutDown: state=2
 ERROR root [0x00000650] [2019-03-01 15:23:45,884] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00000650] [2019-03-01 15:23:45,885] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00000650] [2019-03-01 15:23:45,886] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00000650] [2019-03-01 15:23:45,887] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00000650] [2019-03-01 15:23:45,888] - Halls::~Halls(): 1
 DEBUG root [0x00000650] [2019-03-01 15:23:45,888] - Account::~Account(): 2
 DEBUG root [0x00000650] [2019-03-01 15:23:45,888] - Account::~Account(): 4
 DEBUG root [0x00000650] [2019-03-01 15:23:45,888] - Room::~Room(): 3
  INFO root [0x00000650] [2019-03-01 15:23:45,898] - Script::uninstall(): is successfully!
 DEBUG root [0x00000650] [2019-03-01 15:23:45,898] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000bc0] [2019-03-01 15:43:02,966] - 
  INFO root [0x00000bc0] [2019-03-01 15:43:02,966] - -----------------------------------------------------------------------------------------


  INFO root [0x00000bc0] [2019-03-01 15:43:02,968] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00000bc0] [2019-03-01 15:43:02,968] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00000bc0] [2019-03-01 15:43:02,968] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00000bc0] [2019-03-01 15:43:02,972] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00000bc0] [2019-03-01 15:43:02,972] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00000bc0] [2019-03-01 15:43:02,976] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00000bc0] [2019-03-01 15:43:02,976] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00000bc0] [2019-03-01 15:43:02,979] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:6682 )
  INFO root [0x00000bc0] [2019-03-01 15:43:02,979] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:6682, SOMAXCONN=128.
  INFO root [0x00000bc0] [2019-03-01 15:43:02,979] - server-configs:
  INFO root [0x00000bc0] [2019-03-01 15:43:02,979] - 	gameUpdateHertz : 10
  INFO root [0x00000bc0] [2019-03-01 15:43:02,980] - 	entryScriptFile : kbemain
  INFO root [0x00000bc0] [2019-03-01 15:43:02,980] - 	internalTcpAddr : 192.168.0.148:6682
  INFO root [0x00000bc0] [2019-03-01 15:43:02,980] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00000bc0] [2019-03-01 15:43:02,980] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00000bc0] [2019-03-01 15:43:02,980] - 	componentID : 7001
  WARN root [0x00000bc0] [2019-03-01 15:43:03,301] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00000bc0] [2019-03-01 15:43:03,475] - Components::findLogger: found logger, addr:192.168.0.148:6676
  INFO root [0x00000bc0] [2019-03-01 15:43:03,475] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00000bc0] [2019-03-01 15:43:03,475] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000bc0] [2019-03-01 15:43:03,482] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 13944 ----
  INFO root [0x00000bc0] [2019-03-01 15:43:03,482] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00000bc0] [2019-03-01 15:43:03,482] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000bc0] [2019-03-01 15:43:03,483] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00000bc0] [2019-03-01 15:43:03,658] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00000bc0] [2019-03-01 15:43:03,658] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000bc0] [2019-03-01 15:43:03,750] - loaded entity-script:Account(1).
 DEBUG root [0x00000bc0] [2019-03-01 15:43:03,750] - loaded entity-script:Halls(2).
 DEBUG root [0x00000bc0] [2019-03-01 15:43:03,751] - loaded entity-script:Room(3).
  INFO root [0x00000bc0] [2019-03-01 15:43:03,751] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000bc0] [2019-03-01 15:43:03,751] - TelnetServer server is running on port 40000
  INFO root [0x00000bc0] [2019-03-01 15:43:04,165] - ---- baseapp is running ----
 DEBUG root [0x00000bc0] [2019-03-01 15:43:04,166] - Components::process(): Request for the process of identity...
  WARN root [0x00000bc0] [2019-03-01 15:43:10,341] - Forwarding logs to logger[192.168.0.148:6676/0/0/0]...
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,832] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00000bc0] [2019-03-01 15:44:32,837] - The following logs sent to logger failed:
  WARN root [0x00000bc0] [2019-03-01 15:44:32,837] - ==> [2019-03-01 15:44:32 832] TCPPacketReceiver::processPendingEvents(192.168.0.148:6676): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,837] - ==> [2019-03-01 15:44:32 833] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00000bc0] [2019-03-01 15:44:32,870] - TCPPacketReceiver::processPendingEvents(192.168.0.148:6679): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,871] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00000bc0] [2019-03-01 15:44:32,874] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00000bc0] [2019-03-01 15:44:32,877] - onBaseAppShutDown: state=0
  INFO root [0x00000bc0] [2019-03-01 15:44:32,877] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00000bc0] [2019-03-01 15:44:32,877] - onBaseAppShutDown: state=1
  INFO root [0x00000bc0] [2019-03-01 15:44:32,878] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00000bc0] [2019-03-01 15:44:32,878] - onBaseAppShutDown: state=2
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,892] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,894] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,894] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00000bc0] [2019-03-01 15:44:32,895] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00000bc0] [2019-03-01 15:44:32,896] - Halls::~Halls(): 1
 DEBUG root [0x00000bc0] [2019-03-01 15:44:32,896] - Account::~Account(): 2
 DEBUG root [0x00000bc0] [2019-03-01 15:44:32,896] - Account::~Account(): 4
 DEBUG root [0x00000bc0] [2019-03-01 15:44:32,897] - Room::~Room(): 3
  INFO root [0x00000bc0] [2019-03-01 15:44:32,903] - Script::uninstall(): is successfully!
 DEBUG root [0x00000bc0] [2019-03-01 15:44:32,904] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003f28] [2019-03-01 15:47:39,194] - 
  INFO root [0x00003f28] [2019-03-01 15:47:39,195] - -----------------------------------------------------------------------------------------


  INFO root [0x00003f28] [2019-03-01 15:47:39,196] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003f28] [2019-03-01 15:47:39,197] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003f28] [2019-03-01 15:47:39,197] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003f28] [2019-03-01 15:47:39,202] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003f28] [2019-03-01 15:47:39,202] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003f28] [2019-03-01 15:47:39,206] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003f28] [2019-03-01 15:47:39,206] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003f28] [2019-03-01 15:47:39,210] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7418 )
  INFO root [0x00003f28] [2019-03-01 15:47:39,210] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7418, SOMAXCONN=128.
  INFO root [0x00003f28] [2019-03-01 15:47:39,210] - server-configs:
  INFO root [0x00003f28] [2019-03-01 15:47:39,210] - 	gameUpdateHertz : 10
  INFO root [0x00003f28] [2019-03-01 15:47:39,211] - 	entryScriptFile : kbemain
  INFO root [0x00003f28] [2019-03-01 15:47:39,211] - 	internalTcpAddr : 192.168.0.148:7418
  INFO root [0x00003f28] [2019-03-01 15:47:39,211] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003f28] [2019-03-01 15:47:39,211] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003f28] [2019-03-01 15:47:39,211] - 	componentID : 7001
  WARN root [0x00003f28] [2019-03-01 15:47:39,561] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003f28] [2019-03-01 15:47:39,710] - Components::findLogger: found logger, addr:192.168.0.148:7412
  INFO root [0x00003f28] [2019-03-01 15:47:39,710] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003f28] [2019-03-01 15:47:39,720] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003f28] [2019-03-01 15:47:39,720] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 16196 ----
  INFO root [0x00003f28] [2019-03-01 15:47:39,720] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003f28] [2019-03-01 15:47:39,720] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003f28] [2019-03-01 15:47:39,720] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003f28] [2019-03-01 15:47:39,904] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003f28] [2019-03-01 15:47:39,904] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003f28] [2019-03-01 15:47:40,004] - loaded entity-script:Account(1).
 DEBUG root [0x00003f28] [2019-03-01 15:47:40,004] - loaded entity-script:Halls(2).
 DEBUG root [0x00003f28] [2019-03-01 15:47:40,004] - loaded entity-script:Room(3).
  INFO root [0x00003f28] [2019-03-01 15:47:40,004] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003f28] [2019-03-01 15:47:40,004] - TelnetServer server is running on port 40000
  INFO root [0x00003f28] [2019-03-01 15:47:40,430] - ---- baseapp is running ----
 DEBUG root [0x00003f28] [2019-03-01 15:47:40,430] - Components::process(): Request for the process of identity...
  WARN root [0x00003f28] [2019-03-01 15:47:46,598] - Forwarding logs to logger[192.168.0.148:7412/0/0/0]...
 ERROR root [0x00003f28] [2019-03-01 16:10:37,752] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003f28] [2019-03-01 16:10:37,756] - The following logs sent to logger failed:
  WARN root [0x00003f28] [2019-03-01 16:10:37,757] - ==> [2019-03-01 16:10:37 752] TCPPacketReceiver::processPendingEvents(192.168.0.148:7412): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003f28] [2019-03-01 16:10:37,757] - ==> [2019-03-01 16:10:37 754] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003f28] [2019-03-01 16:10:37,797] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7414): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003f28] [2019-03-01 16:10:37,798] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003f28] [2019-03-01 16:10:37,804] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003f28] [2019-03-01 16:10:37,808] - onBaseAppShutDown: state=0
  INFO root [0x00003f28] [2019-03-01 16:10:37,808] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003f28] [2019-03-01 16:10:37,808] - onBaseAppShutDown: state=1
  INFO root [0x00003f28] [2019-03-01 16:10:37,809] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003f28] [2019-03-01 16:10:37,809] - onBaseAppShutDown: state=2
 ERROR root [0x00003f28] [2019-03-01 16:10:37,826] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,827] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,828] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,829] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,830] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,830] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,831] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,832] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,833] - Account::onCellWriteToDBCompleted(8): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,833] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,834] - Account::onCellWriteToDBCompleted(10): not found dbmgr!
 ERROR root [0x00003f28] [2019-03-01 16:10:37,835] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,836] - Halls::~Halls(): 1
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,837] - Account::~Account(): 2
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,837] - Account::~Account(): 4
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,837] - Room::~Room(): 3
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,838] - Account::~Account(): 5
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,838] - Account::~Account(): 7
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,839] - Room::~Room(): 6
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,839] - Account::~Account(): 8
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,839] - Account::~Account(): 10
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,839] - Room::~Room(): 9
  INFO root [0x00003f28] [2019-03-01 16:10:37,852] - Script::uninstall(): is successfully!
 DEBUG root [0x00003f28] [2019-03-01 16:10:37,852] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003a58] [2019-03-01 16:10:40,548] - 
  INFO root [0x00003a58] [2019-03-01 16:10:40,549] - -----------------------------------------------------------------------------------------


  INFO root [0x00003a58] [2019-03-01 16:10:40,551] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003a58] [2019-03-01 16:10:40,552] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003a58] [2019-03-01 16:10:40,552] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003a58] [2019-03-01 16:10:40,559] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003a58] [2019-03-01 16:10:40,559] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003a58] [2019-03-01 16:10:40,563] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003a58] [2019-03-01 16:10:40,564] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003a58] [2019-03-01 16:10:40,567] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10986 )
  INFO root [0x00003a58] [2019-03-01 16:10:40,568] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10986, SOMAXCONN=128.
  INFO root [0x00003a58] [2019-03-01 16:10:40,568] - server-configs:
  INFO root [0x00003a58] [2019-03-01 16:10:40,568] - 	gameUpdateHertz : 10
  INFO root [0x00003a58] [2019-03-01 16:10:40,569] - 	entryScriptFile : kbemain
  INFO root [0x00003a58] [2019-03-01 16:10:40,569] - 	internalTcpAddr : 192.168.0.148:10986
  INFO root [0x00003a58] [2019-03-01 16:10:40,569] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003a58] [2019-03-01 16:10:40,569] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003a58] [2019-03-01 16:10:40,569] - 	componentID : 7001
  WARN root [0x00003a58] [2019-03-01 16:10:40,874] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003a58] [2019-03-01 16:10:41,115] - Components::findLogger: found logger, addr:192.168.0.148:10989
  INFO root [0x00003a58] [2019-03-01 16:10:41,115] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003a58] [2019-03-01 16:10:41,115] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a58] [2019-03-01 16:10:41,122] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 14932 ----
  INFO root [0x00003a58] [2019-03-01 16:10:41,122] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003a58] [2019-03-01 16:10:41,122] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003a58] [2019-03-01 16:10:41,123] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003a58] [2019-03-01 16:10:41,304] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003a58] [2019-03-01 16:10:41,304] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003a58] [2019-03-01 16:10:41,420] - loaded entity-script:Account(1).
 DEBUG root [0x00003a58] [2019-03-01 16:10:41,421] - loaded entity-script:Halls(2).
 DEBUG root [0x00003a58] [2019-03-01 16:10:41,422] - loaded entity-script:Room(3).
  INFO root [0x00003a58] [2019-03-01 16:10:41,422] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003a58] [2019-03-01 16:10:41,422] - TelnetServer server is running on port 40000
  INFO root [0x00003a58] [2019-03-01 16:10:41,749] - ---- baseapp is running ----
 DEBUG root [0x00003a58] [2019-03-01 16:10:41,750] - Components::process(): Request for the process of identity...
  WARN root [0x00003a58] [2019-03-01 16:10:47,902] - Forwarding logs to logger[192.168.0.148:10989/0/0/0]...
 ERROR root [0x00003a58] [2019-03-01 16:29:18,821] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003a58] [2019-03-01 16:29:18,828] - The following logs sent to logger failed:
  WARN root [0x00003a58] [2019-03-01 16:29:18,828] - ==> [2019-03-01 16:29:18 820] TCPPacketReceiver::processPendingEvents(192.168.0.148:10989): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a58] [2019-03-01 16:29:18,828] - ==> [2019-03-01 16:29:18 822] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003a58] [2019-03-01 16:29:18,871] - TCPPacketReceiver::processPendingEvents(192.168.0.148:10985): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a58] [2019-03-01 16:29:18,873] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003a58] [2019-03-01 16:29:18,881] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003a58] [2019-03-01 16:29:18,887] - onBaseAppShutDown: state=0
  INFO root [0x00003a58] [2019-03-01 16:29:18,887] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003a58] [2019-03-01 16:29:18,887] - onBaseAppShutDown: state=1
  INFO root [0x00003a58] [2019-03-01 16:29:18,888] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003a58] [2019-03-01 16:29:18,888] - onBaseAppShutDown: state=2
 ERROR root [0x00003a58] [2019-03-01 16:29:18,910] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,912] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,912] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,914] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,914] - Account::onCellWriteToDBCompleted(2005): not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,915] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,916] - Account::onCellWriteToDBCompleted(2007): not found dbmgr!
 ERROR root [0x00003a58] [2019-03-01 16:29:18,918] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,920] - Halls::~Halls(): 2001
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,920] - Account::~Account(): 2002
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,921] - Account::~Account(): 2004
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,921] - Room::~Room(): 2003
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,921] - Account::~Account(): 2005
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,921] - Account::~Account(): 2007
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,922] - Room::~Room(): 2006
  INFO root [0x00003a58] [2019-03-01 16:29:18,938] - Script::uninstall(): is successfully!
 DEBUG root [0x00003a58] [2019-03-01 16:29:18,938] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003208] [2019-03-01 16:29:33,474] - 
  INFO root [0x00003208] [2019-03-01 16:29:33,478] - -----------------------------------------------------------------------------------------


  INFO root [0x00003208] [2019-03-01 16:29:33,481] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003208] [2019-03-01 16:29:33,483] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003208] [2019-03-01 16:29:33,484] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003208] [2019-03-01 16:29:33,500] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003208] [2019-03-01 16:29:33,501] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003208] [2019-03-01 16:29:33,506] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003208] [2019-03-01 16:29:33,507] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003208] [2019-03-01 16:29:33,511] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:14038 )
  INFO root [0x00003208] [2019-03-01 16:29:33,511] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:14038, SOMAXCONN=128.
  INFO root [0x00003208] [2019-03-01 16:29:33,512] - server-configs:
  INFO root [0x00003208] [2019-03-01 16:29:33,512] - 	gameUpdateHertz : 10
  INFO root [0x00003208] [2019-03-01 16:29:33,512] - 	entryScriptFile : kbemain
  INFO root [0x00003208] [2019-03-01 16:29:33,512] - 	internalTcpAddr : 192.168.0.148:14038
  INFO root [0x00003208] [2019-03-01 16:29:33,513] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003208] [2019-03-01 16:29:33,513] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003208] [2019-03-01 16:29:33,513] - 	componentID : 7001
  WARN root [0x00003208] [2019-03-01 16:29:34,094] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003208] [2019-03-01 16:29:34,585] - Components::findLogger: found logger, addr:192.168.0.148:14041
  INFO root [0x00003208] [2019-03-01 16:29:34,585] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003208] [2019-03-01 16:29:34,585] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003208] [2019-03-01 16:29:34,592] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 12796 ----
  INFO root [0x00003208] [2019-03-01 16:29:34,593] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003208] [2019-03-01 16:29:34,593] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003208] [2019-03-01 16:29:34,594] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003208] [2019-03-01 16:29:34,844] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003208] [2019-03-01 16:29:34,845] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003208] [2019-03-01 16:29:35,025] - loaded entity-script:Account(1).
 DEBUG root [0x00003208] [2019-03-01 16:29:35,026] - loaded entity-script:Halls(2).
 DEBUG root [0x00003208] [2019-03-01 16:29:35,027] - loaded entity-script:Room(3).
  INFO root [0x00003208] [2019-03-01 16:29:35,027] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003208] [2019-03-01 16:29:35,027] - TelnetServer server is running on port 40000
  INFO root [0x00003208] [2019-03-01 16:29:36,206] - ---- baseapp is running ----
 DEBUG root [0x00003208] [2019-03-01 16:29:36,206] - Components::process(): Request for the process of identity...
  WARN root [0x00003208] [2019-03-01 16:29:42,396] - Forwarding logs to logger[192.168.0.148:14041/0/0/0]...
 ERROR root [0x00003208] [2019-03-01 16:36:46,648] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003208] [2019-03-01 16:36:46,654] - The following logs sent to logger failed:
  WARN root [0x00003208] [2019-03-01 16:36:46,654] - ==> [2019-03-01 16:36:46 647] TCPPacketReceiver::processPendingEvents(192.168.0.148:14041): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003208] [2019-03-01 16:36:46,654] - ==> [2019-03-01 16:36:46 649] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003208] [2019-03-01 16:36:46,701] - TCPPacketReceiver::processPendingEvents(192.168.0.148:14032): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003208] [2019-03-01 16:36:46,701] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003208] [2019-03-01 16:36:46,707] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003208] [2019-03-01 16:36:46,710] - onBaseAppShutDown: state=0
  INFO root [0x00003208] [2019-03-01 16:36:46,710] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003208] [2019-03-01 16:36:46,711] - onBaseAppShutDown: state=1
  INFO root [0x00003208] [2019-03-01 16:36:46,711] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003208] [2019-03-01 16:36:46,711] - onBaseAppShutDown: state=2
 ERROR root [0x00003208] [2019-03-01 16:36:46,724] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,726] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,726] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,728] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,728] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,729] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,730] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003208] [2019-03-01 16:36:46,731] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003208] [2019-03-01 16:36:46,732] - Halls::~Halls(): 1
 DEBUG root [0x00003208] [2019-03-01 16:36:46,732] - Account::~Account(): 2
 DEBUG root [0x00003208] [2019-03-01 16:36:46,733] - Account::~Account(): 4
 DEBUG root [0x00003208] [2019-03-01 16:36:46,733] - Room::~Room(): 3
 DEBUG root [0x00003208] [2019-03-01 16:36:46,733] - Account::~Account(): 5
 DEBUG root [0x00003208] [2019-03-01 16:36:46,733] - Account::~Account(): 7
 DEBUG root [0x00003208] [2019-03-01 16:36:46,733] - Room::~Room(): 6
  INFO root [0x00003208] [2019-03-01 16:36:46,748] - Script::uninstall(): is successfully!
 DEBUG root [0x00003208] [2019-03-01 16:36:46,749] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003ff8] [2019-03-01 16:38:50,792] - 
  INFO root [0x00003ff8] [2019-03-01 16:38:50,794] - -----------------------------------------------------------------------------------------


  INFO root [0x00003ff8] [2019-03-01 16:38:50,796] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003ff8] [2019-03-01 16:38:50,797] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003ff8] [2019-03-01 16:38:50,797] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003ff8] [2019-03-01 16:38:50,809] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003ff8] [2019-03-01 16:38:50,809] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003ff8] [2019-03-01 16:38:50,815] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003ff8] [2019-03-01 16:38:50,815] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003ff8] [2019-03-01 16:38:50,819] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7130 )
  INFO root [0x00003ff8] [2019-03-01 16:38:50,819] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7130, SOMAXCONN=128.
  INFO root [0x00003ff8] [2019-03-01 16:38:50,819] - server-configs:
  INFO root [0x00003ff8] [2019-03-01 16:38:50,820] - 	gameUpdateHertz : 10
  INFO root [0x00003ff8] [2019-03-01 16:38:50,820] - 	entryScriptFile : kbemain
  INFO root [0x00003ff8] [2019-03-01 16:38:50,820] - 	internalTcpAddr : 192.168.0.148:7130
  INFO root [0x00003ff8] [2019-03-01 16:38:50,821] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003ff8] [2019-03-01 16:38:50,821] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003ff8] [2019-03-01 16:38:50,821] - 	componentID : 7001
  WARN root [0x00003ff8] [2019-03-01 16:38:51,139] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003ff8] [2019-03-01 16:38:51,426] - Components::findLogger: found logger, addr:192.168.0.148:7134
  INFO root [0x00003ff8] [2019-03-01 16:38:51,426] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003ff8] [2019-03-01 16:38:51,426] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003ff8] [2019-03-01 16:38:51,433] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 14736 ----
  INFO root [0x00003ff8] [2019-03-01 16:38:51,433] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003ff8] [2019-03-01 16:38:51,434] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003ff8] [2019-03-01 16:38:51,434] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003ff8] [2019-03-01 16:38:51,614] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003ff8] [2019-03-01 16:38:51,614] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003ff8] [2019-03-01 16:38:51,702] - loaded entity-script:Account(1).
 DEBUG root [0x00003ff8] [2019-03-01 16:38:51,702] - loaded entity-script:Halls(2).
 DEBUG root [0x00003ff8] [2019-03-01 16:38:51,703] - loaded entity-script:Room(3).
  INFO root [0x00003ff8] [2019-03-01 16:38:51,703] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003ff8] [2019-03-01 16:38:51,703] - TelnetServer server is running on port 40000
  INFO root [0x00003ff8] [2019-03-01 16:38:52,078] - ---- baseapp is running ----
 DEBUG root [0x00003ff8] [2019-03-01 16:38:52,079] - Components::process(): Request for the process of identity...
  WARN root [0x00003ff8] [2019-03-01 16:38:58,242] - Forwarding logs to logger[192.168.0.148:7134/0/0/0]...
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,656] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003ff8] [2019-03-01 16:46:14,665] - The following logs sent to logger failed:
  WARN root [0x00003ff8] [2019-03-01 16:46:14,666] - ==> [2019-03-01 16:46:14 656] TCPPacketReceiver::processPendingEvents(192.168.0.148:7134): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,666] - ==> [2019-03-01 16:46:14 658] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003ff8] [2019-03-01 16:46:14,697] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7127): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,698] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003ff8] [2019-03-01 16:46:14,703] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003ff8] [2019-03-01 16:46:14,705] - onBaseAppShutDown: state=0
  INFO root [0x00003ff8] [2019-03-01 16:46:14,706] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003ff8] [2019-03-01 16:46:14,706] - onBaseAppShutDown: state=1
  INFO root [0x00003ff8] [2019-03-01 16:46:14,707] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003ff8] [2019-03-01 16:46:14,707] - onBaseAppShutDown: state=2
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,721] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,722] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,723] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,723] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,724] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,724] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,726] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003ff8] [2019-03-01 16:46:14,727] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,728] - Halls::~Halls(): 1
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,728] - Account::~Account(): 2
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,728] - Account::~Account(): 4
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,728] - Room::~Room(): 3
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,728] - Account::~Account(): 5
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,729] - Account::~Account(): 7
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,729] - Room::~Room(): 6
  INFO root [0x00003ff8] [2019-03-01 16:46:14,740] - Script::uninstall(): is successfully!
 DEBUG root [0x00003ff8] [2019-03-01 16:46:14,741] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000154c] [2019-03-01 16:46:46,102] - 
  INFO root [0x0000154c] [2019-03-01 16:46:46,102] - -----------------------------------------------------------------------------------------


  INFO root [0x0000154c] [2019-03-01 16:46:46,105] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x0000154c] [2019-03-01 16:46:46,105] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x0000154c] [2019-03-01 16:46:46,105] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x0000154c] [2019-03-01 16:46:46,109] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x0000154c] [2019-03-01 16:46:46,109] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x0000154c] [2019-03-01 16:46:46,112] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x0000154c] [2019-03-01 16:46:46,113] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x0000154c] [2019-03-01 16:46:46,115] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:8382 )
  INFO root [0x0000154c] [2019-03-01 16:46:46,115] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:8382, SOMAXCONN=128.
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - server-configs:
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	gameUpdateHertz : 10
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	entryScriptFile : kbemain
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	internalTcpAddr : 192.168.0.148:8382
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x0000154c] [2019-03-01 16:46:46,116] - 	componentID : 7001
  WARN root [0x0000154c] [2019-03-01 16:46:46,442] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x0000154c] [2019-03-01 16:46:46,792] - Components::findLogger: found logger, addr:192.168.0.148:8375
  INFO root [0x0000154c] [2019-03-01 16:46:46,792] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000154c] [2019-03-01 16:46:46,792] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000154c] [2019-03-01 16:46:46,799] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 15076 ----
  INFO root [0x0000154c] [2019-03-01 16:46:46,799] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x0000154c] [2019-03-01 16:46:46,800] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000154c] [2019-03-01 16:46:46,800] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000154c] [2019-03-01 16:46:46,988] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000154c] [2019-03-01 16:46:46,988] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000154c] [2019-03-01 16:46:47,108] - loaded entity-script:Account(1).
 DEBUG root [0x0000154c] [2019-03-01 16:46:47,109] - loaded entity-script:Halls(2).
 DEBUG root [0x0000154c] [2019-03-01 16:46:47,109] - loaded entity-script:Room(3).
  INFO root [0x0000154c] [2019-03-01 16:46:47,109] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000154c] [2019-03-01 16:46:47,110] - TelnetServer server is running on port 40000
  INFO root [0x0000154c] [2019-03-01 16:46:47,460] - ---- baseapp is running ----
 DEBUG root [0x0000154c] [2019-03-01 16:46:47,461] - Components::process(): Request for the process of identity...
  WARN root [0x0000154c] [2019-03-01 16:46:53,618] - Forwarding logs to logger[192.168.0.148:8375/0/0/0]...
 ERROR root [0x0000154c] [2019-03-01 16:49:28,379] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000154c] [2019-03-01 16:49:28,383] - The following logs sent to logger failed:
  WARN root [0x0000154c] [2019-03-01 16:49:28,384] - ==> [2019-03-01 16:49:28 379] TCPPacketReceiver::processPendingEvents(192.168.0.148:8375): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000154c] [2019-03-01 16:49:28,384] - ==> [2019-03-01 16:49:28 380] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x0000154c] [2019-03-01 16:49:28,460] - TCPPacketReceiver::processPendingEvents(192.168.0.148:8377): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000154c] [2019-03-01 16:49:28,464] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000154c] [2019-03-01 16:49:28,469] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000154c] [2019-03-01 16:49:28,470] - onBaseAppShutDown: state=0
  INFO root [0x0000154c] [2019-03-01 16:49:28,471] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000154c] [2019-03-01 16:49:28,471] - onBaseAppShutDown: state=1
  INFO root [0x0000154c] [2019-03-01 16:49:28,471] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000154c] [2019-03-01 16:49:28,472] - onBaseAppShutDown: state=2
 ERROR root [0x0000154c] [2019-03-01 16:49:28,497] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,498] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,499] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,500] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,500] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,501] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,502] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x0000154c] [2019-03-01 16:49:28,503] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,504] - Halls::~Halls(): 1
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,504] - Account::~Account(): 2
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,504] - Account::~Account(): 4
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,504] - Room::~Room(): 3
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,505] - Account::~Account(): 5
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,505] - Account::~Account(): 7
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,505] - Room::~Room(): 6
  INFO root [0x0000154c] [2019-03-01 16:49:28,521] - Script::uninstall(): is successfully!
 DEBUG root [0x0000154c] [2019-03-01 16:49:28,521] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003fc4] [2019-03-01 16:58:37,014] - 
  INFO root [0x00003fc4] [2019-03-01 16:58:37,014] - -----------------------------------------------------------------------------------------


  INFO root [0x00003fc4] [2019-03-01 16:58:37,016] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003fc4] [2019-03-01 16:58:37,016] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003fc4] [2019-03-01 16:58:37,016] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003fc4] [2019-03-01 16:58:37,021] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003fc4] [2019-03-01 16:58:37,021] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003fc4] [2019-03-01 16:58:37,025] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003fc4] [2019-03-01 16:58:37,025] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003fc4] [2019-03-01 16:58:37,028] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7012 )
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7012, SOMAXCONN=128.
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - server-configs:
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	gameUpdateHertz : 10
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	entryScriptFile : kbemain
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	internalTcpAddr : 192.168.0.148:7012
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003fc4] [2019-03-01 16:58:37,029] - 	componentID : 7001
  WARN root [0x00003fc4] [2019-03-01 16:58:37,414] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003fc4] [2019-03-01 16:58:37,601] - Components::findLogger: found logger, addr:192.168.0.148:7005
  INFO root [0x00003fc4] [2019-03-01 16:58:37,601] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003fc4] [2019-03-01 16:58:37,602] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fc4] [2019-03-01 16:58:37,608] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 2388 ----
  INFO root [0x00003fc4] [2019-03-01 16:58:37,608] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003fc4] [2019-03-01 16:58:37,609] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003fc4] [2019-03-01 16:58:37,609] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003fc4] [2019-03-01 16:58:37,799] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003fc4] [2019-03-01 16:58:37,799] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003fc4] [2019-03-01 16:58:37,916] - loaded entity-script:Account(1).
 DEBUG root [0x00003fc4] [2019-03-01 16:58:37,916] - loaded entity-script:Halls(2).
 DEBUG root [0x00003fc4] [2019-03-01 16:58:37,916] - loaded entity-script:Room(3).
  INFO root [0x00003fc4] [2019-03-01 16:58:37,917] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003fc4] [2019-03-01 16:58:37,917] - TelnetServer server is running on port 40000
  INFO root [0x00003fc4] [2019-03-01 16:58:38,324] - ---- baseapp is running ----
 DEBUG root [0x00003fc4] [2019-03-01 16:58:38,324] - Components::process(): Request for the process of identity...
  WARN root [0x00003fc4] [2019-03-01 16:58:44,452] - Forwarding logs to logger[192.168.0.148:7005/0/0/0]...
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,558] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003fc4] [2019-03-01 17:08:43,563] - The following logs sent to logger failed:
  WARN root [0x00003fc4] [2019-03-01 17:08:43,563] - ==> [2019-03-01 17:08:43 558] TCPPacketReceiver::processPendingEvents(192.168.0.148:7005): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,564] - ==> [2019-03-01 17:08:43 559] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003fc4] [2019-03-01 17:08:43,605] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7007): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,606] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003fc4] [2019-03-01 17:08:43,611] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003fc4] [2019-03-01 17:08:43,614] - onBaseAppShutDown: state=0
  INFO root [0x00003fc4] [2019-03-01 17:08:43,614] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003fc4] [2019-03-01 17:08:43,614] - onBaseAppShutDown: state=1
  INFO root [0x00003fc4] [2019-03-01 17:08:43,614] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003fc4] [2019-03-01 17:08:43,614] - onBaseAppShutDown: state=2
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,629] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,633] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,633] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,634] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,635] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,636] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,636] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003fc4] [2019-03-01 17:08:43,637] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Halls::~Halls(): 1
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Account::~Account(): 2
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Account::~Account(): 4
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Room::~Room(): 3
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Account::~Account(): 5
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Account::~Account(): 7
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,638] - Room::~Room(): 6
  INFO root [0x00003fc4] [2019-03-01 17:08:43,651] - Script::uninstall(): is successfully!
 DEBUG root [0x00003fc4] [2019-03-01 17:08:43,651] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003a14] [2019-03-01 17:10:29,707] - 
  INFO root [0x00003a14] [2019-03-01 17:10:29,709] - -----------------------------------------------------------------------------------------


  INFO root [0x00003a14] [2019-03-01 17:10:29,710] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003a14] [2019-03-01 17:10:29,711] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003a14] [2019-03-01 17:10:29,711] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003a14] [2019-03-01 17:10:29,718] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003a14] [2019-03-01 17:10:29,719] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003a14] [2019-03-01 17:10:29,722] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003a14] [2019-03-01 17:10:29,722] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003a14] [2019-03-01 17:10:29,726] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:8951 )
  INFO root [0x00003a14] [2019-03-01 17:10:29,726] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:8951, SOMAXCONN=128.
  INFO root [0x00003a14] [2019-03-01 17:10:29,726] - server-configs:
  INFO root [0x00003a14] [2019-03-01 17:10:29,727] - 	gameUpdateHertz : 10
  INFO root [0x00003a14] [2019-03-01 17:10:29,727] - 	entryScriptFile : kbemain
  INFO root [0x00003a14] [2019-03-01 17:10:29,727] - 	internalTcpAddr : 192.168.0.148:8951
  INFO root [0x00003a14] [2019-03-01 17:10:29,728] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003a14] [2019-03-01 17:10:29,728] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003a14] [2019-03-01 17:10:29,728] - 	componentID : 7001
  WARN root [0x00003a14] [2019-03-01 17:10:30,082] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003a14] [2019-03-01 17:10:30,354] - Components::findLogger: found logger, addr:192.168.0.148:8950
  INFO root [0x00003a14] [2019-03-01 17:10:30,355] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003a14] [2019-03-01 17:10:30,355] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a14] [2019-03-01 17:10:30,362] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 1364 ----
  INFO root [0x00003a14] [2019-03-01 17:10:30,362] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003a14] [2019-03-01 17:10:30,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003a14] [2019-03-01 17:10:30,363] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003a14] [2019-03-01 17:10:30,566] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003a14] [2019-03-01 17:10:30,566] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003a14] [2019-03-01 17:10:30,699] - loaded entity-script:Account(1).
 DEBUG root [0x00003a14] [2019-03-01 17:10:30,699] - loaded entity-script:Halls(2).
 DEBUG root [0x00003a14] [2019-03-01 17:10:30,700] - loaded entity-script:Room(3).
  INFO root [0x00003a14] [2019-03-01 17:10:30,700] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003a14] [2019-03-01 17:10:30,701] - TelnetServer server is running on port 40000
  INFO root [0x00003a14] [2019-03-01 17:10:31,195] - ---- baseapp is running ----
 DEBUG root [0x00003a14] [2019-03-01 17:10:31,196] - Components::process(): Request for the process of identity...
  WARN root [0x00003a14] [2019-03-01 17:10:37,349] - Forwarding logs to logger[192.168.0.148:8950/0/0/0]...
 ERROR root [0x00003a14] [2019-03-01 17:15:27,481] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003a14] [2019-03-01 17:15:27,485] - The following logs sent to logger failed:
  WARN root [0x00003a14] [2019-03-01 17:15:27,485] - ==> [2019-03-01 17:15:27 481] TCPPacketReceiver::processPendingEvents(192.168.0.148:8950): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a14] [2019-03-01 17:15:27,486] - ==> [2019-03-01 17:15:27 482] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003a14] [2019-03-01 17:15:27,533] - TCPPacketReceiver::processPendingEvents(192.168.0.148:8946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a14] [2019-03-01 17:15:27,533] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003a14] [2019-03-01 17:15:27,540] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003a14] [2019-03-01 17:15:27,542] - onBaseAppShutDown: state=0
  INFO root [0x00003a14] [2019-03-01 17:15:27,543] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003a14] [2019-03-01 17:15:27,543] - onBaseAppShutDown: state=1
  INFO root [0x00003a14] [2019-03-01 17:15:27,543] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003a14] [2019-03-01 17:15:27,543] - onBaseAppShutDown: state=2
 ERROR root [0x00003a14] [2019-03-01 17:15:27,558] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003a14] [2019-03-01 17:15:27,560] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003a14] [2019-03-01 17:15:27,561] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003a14] [2019-03-01 17:15:27,562] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003a14] [2019-03-01 17:15:27,563] - Halls::~Halls(): 1
 DEBUG root [0x00003a14] [2019-03-01 17:15:27,563] - Account::~Account(): 2
 DEBUG root [0x00003a14] [2019-03-01 17:15:27,563] - Account::~Account(): 4
 DEBUG root [0x00003a14] [2019-03-01 17:15:27,564] - Room::~Room(): 3
  INFO root [0x00003a14] [2019-03-01 17:15:27,572] - Script::uninstall(): is successfully!
 DEBUG root [0x00003a14] [2019-03-01 17:15:27,573] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003bd4] [2019-03-01 17:30:39,852] - 
  INFO root [0x00003bd4] [2019-03-01 17:30:39,853] - -----------------------------------------------------------------------------------------


  INFO root [0x00003bd4] [2019-03-01 17:30:39,855] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003bd4] [2019-03-01 17:30:39,856] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003bd4] [2019-03-01 17:30:39,856] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003bd4] [2019-03-01 17:30:39,860] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003bd4] [2019-03-01 17:30:39,861] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003bd4] [2019-03-01 17:30:39,864] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003bd4] [2019-03-01 17:30:39,865] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003bd4] [2019-03-01 17:30:39,868] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:12237 )
  INFO root [0x00003bd4] [2019-03-01 17:30:39,869] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:12237, SOMAXCONN=128.
  INFO root [0x00003bd4] [2019-03-01 17:30:39,869] - server-configs:
  INFO root [0x00003bd4] [2019-03-01 17:30:39,869] - 	gameUpdateHertz : 10
  INFO root [0x00003bd4] [2019-03-01 17:30:39,870] - 	entryScriptFile : kbemain
  INFO root [0x00003bd4] [2019-03-01 17:30:39,870] - 	internalTcpAddr : 192.168.0.148:12237
  INFO root [0x00003bd4] [2019-03-01 17:30:39,870] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003bd4] [2019-03-01 17:30:39,870] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003bd4] [2019-03-01 17:30:39,870] - 	componentID : 7001
  WARN root [0x00003bd4] [2019-03-01 17:30:40,262] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003bd4] [2019-03-01 17:30:40,485] - Components::findLogger: found logger, addr:192.168.0.148:12233
  INFO root [0x00003bd4] [2019-03-01 17:30:40,486] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003bd4] [2019-03-01 17:30:40,486] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003bd4] [2019-03-01 17:30:40,491] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 13260 ----
  INFO root [0x00003bd4] [2019-03-01 17:30:40,491] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003bd4] [2019-03-01 17:30:40,491] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003bd4] [2019-03-01 17:30:40,491] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003bd4] [2019-03-01 17:30:40,698] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003bd4] [2019-03-01 17:30:40,698] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003bd4] [2019-03-01 17:30:40,825] - loaded entity-script:Account(1).
 DEBUG root [0x00003bd4] [2019-03-01 17:30:40,825] - loaded entity-script:Halls(2).
 DEBUG root [0x00003bd4] [2019-03-01 17:30:40,826] - loaded entity-script:Room(3).
  INFO root [0x00003bd4] [2019-03-01 17:30:40,826] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003bd4] [2019-03-01 17:30:40,827] - TelnetServer server is running on port 40000
  INFO root [0x00003bd4] [2019-03-01 17:30:41,389] - ---- baseapp is running ----
 DEBUG root [0x00003bd4] [2019-03-01 17:30:41,390] - Components::process(): Request for the process of identity...
  WARN root [0x00003bd4] [2019-03-01 17:30:47,554] - Forwarding logs to logger[192.168.0.148:12233/0/0/0]...
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,685] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003bd4] [2019-03-01 17:37:13,689] - The following logs sent to logger failed:
  WARN root [0x00003bd4] [2019-03-01 17:37:13,690] - ==> [2019-03-01 17:37:13 685] TCPPacketReceiver::processPendingEvents(192.168.0.148:12233): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,690] - ==> [2019-03-01 17:37:13 686] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003bd4] [2019-03-01 17:37:13,730] - TCPPacketReceiver::processPendingEvents(192.168.0.148:12235): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,732] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003bd4] [2019-03-01 17:37:13,738] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003bd4] [2019-03-01 17:37:13,740] - onBaseAppShutDown: state=0
  INFO root [0x00003bd4] [2019-03-01 17:37:13,740] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003bd4] [2019-03-01 17:37:13,741] - onBaseAppShutDown: state=1
  INFO root [0x00003bd4] [2019-03-01 17:37:13,741] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003bd4] [2019-03-01 17:37:13,741] - onBaseAppShutDown: state=2
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,754] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,755] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,757] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,758] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,759] - Account::onCellWriteToDBCompleted(5): not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,759] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,760] - Account::onCellWriteToDBCompleted(7): not found dbmgr!
 ERROR root [0x00003bd4] [2019-03-01 17:37:13,761] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,762] - Halls::~Halls(): 1
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,762] - Account::~Account(): 2
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,762] - Account::~Account(): 4
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,762] - Room::~Room(): 3
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,763] - Account::~Account(): 5
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,763] - Account::~Account(): 7
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,763] - Room::~Room(): 6
  INFO root [0x00003bd4] [2019-03-01 17:37:13,772] - Script::uninstall(): is successfully!
 DEBUG root [0x00003bd4] [2019-03-01 17:37:13,772] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000211c] [2019-03-01 18:55:01,622] - 
  INFO root [0x0000211c] [2019-03-01 18:55:01,628] - -----------------------------------------------------------------------------------------


  INFO root [0x0000211c] [2019-03-01 18:55:01,628] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x0000211c] [2019-03-01 18:55:01,628] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x0000211c] [2019-03-01 18:55:01,632] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:9444 )
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:9444, SOMAXCONN=128.
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - server-configs:
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	gameUpdateHertz : 10
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	entryScriptFile : kbemain
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	internalTcpAddr : 192.168.0.148:9444
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x0000211c] [2019-03-01 18:55:01,638] - 	componentID : 7001
  WARN root [0x0000211c] [2019-03-01 18:55:01,931] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x0000211c] [2019-03-01 18:55:02,137] - Components::findLogger: found logger, addr:192.168.0.148:9446
  INFO root [0x0000211c] [2019-03-01 18:55:02,138] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000211c] [2019-03-01 18:55:02,138] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000211c] [2019-03-01 18:55:02,140] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 6180 ----
  INFO root [0x0000211c] [2019-03-01 18:55:02,140] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x0000211c] [2019-03-01 18:55:02,140] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000211c] [2019-03-01 18:55:02,140] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000211c] [2019-03-01 18:55:02,321] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000211c] [2019-03-01 18:55:02,321] - Script::install(): KBExtra is successfully!
 ERROR root [0x0000211c] [2019-03-01 18:55:02,349] - TiXmlNode::openXML: D:/kbengine-2.4.2/first_server_assets/scripts/entity_defs/Room.def, error!
 ERROR root [0x0000211c] [2019-03-01 18:55:02,349] - app::initialize(): initialization failed!
  INFO root [0x0000211c] [2019-03-01 18:55:02,349] - Script::uninstall(): is successfully!
 DEBUG root [0x0000211c] [2019-03-01 18:55:02,349] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000211c] [2019-03-01 18:55:02,681] - ThreadPool::destroy(): waiting for thread(2)[0x20ec770,0x20ec7d8,], try=1
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - TPThread::~TPThread(): 0x20ec770
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - TPThread::~TPThread(): 0x20ec7d8
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - ThreadPool::destroy(): successfully!
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - Bundle::destroyObjPool(): size 13.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - Channel::destroyObjPool(): size 15.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - Address::destroyObjPool(): size 0.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x0000211c] [2019-03-01 18:55:03,108] - UDPPacketReceiver::destroyObjPool(): size 0.
  WARN root [0x0000211c] [2019-03-01 18:55:03,108] - Forwarding logs to logger[192.168.0.148:9446/0/0/0]...
  INFO root [0x0000211c] [2019-03-01 18:55:09,658] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x00002334] [2019-03-01 18:56:17,568] - 
  INFO root [0x00002334] [2019-03-01 18:56:17,568] - -----------------------------------------------------------------------------------------


  INFO root [0x00002334] [2019-03-01 18:56:17,572] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00002334] [2019-03-01 18:56:17,572] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00002334] [2019-03-01 18:56:17,572] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00002334] [2019-03-01 18:56:17,578] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00002334] [2019-03-01 18:56:17,578] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00002334] [2019-03-01 18:56:17,581] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00002334] [2019-03-01 18:56:17,581] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:9661 )
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:9661, SOMAXCONN=128.
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - server-configs:
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	gameUpdateHertz : 10
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	entryScriptFile : kbemain
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	internalTcpAddr : 192.168.0.148:9661
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00002334] [2019-03-01 18:56:17,588] - 	componentID : 7001
  WARN root [0x00002334] [2019-03-01 18:56:17,877] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00002334] [2019-03-01 18:56:18,136] - Components::findLogger: found logger, addr:192.168.0.148:9663
  INFO root [0x00002334] [2019-03-01 18:56:18,136] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00002334] [2019-03-01 18:56:18,136] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002334] [2019-03-01 18:56:18,144] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 10508 ----
  INFO root [0x00002334] [2019-03-01 18:56:18,144] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00002334] [2019-03-01 18:56:18,144] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002334] [2019-03-01 18:56:18,144] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00002334] [2019-03-01 18:56:18,334] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00002334] [2019-03-01 18:56:18,334] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002334] [2019-03-01 18:56:18,508] - loaded entity-script:Account(1).
 DEBUG root [0x00002334] [2019-03-01 18:56:18,508] - loaded entity-script:Halls(2).
 DEBUG root [0x00002334] [2019-03-01 18:56:18,508] - loaded entity-script:Room(3).
  INFO root [0x00002334] [2019-03-01 18:56:18,508] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002334] [2019-03-01 18:56:18,508] - TelnetServer server is running on port 40000
  INFO root [0x00002334] [2019-03-01 18:56:18,943] - ---- baseapp is running ----
 DEBUG root [0x00002334] [2019-03-01 18:56:18,943] - Components::process(): Request for the process of identity...
  WARN root [0x00002334] [2019-03-01 18:56:25,169] - Forwarding logs to logger[192.168.0.148:9663/0/0/0]...
 ERROR root [0x00002334] [2019-03-01 19:03:55,305] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00002334] [2019-03-01 19:03:55,309] - The following logs sent to logger failed:
  WARN root [0x00002334] [2019-03-01 19:03:55,310] - ==> [2019-03-01 19:03:55 305] TCPPacketReceiver::processPendingEvents(192.168.0.148:9663): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002334] [2019-03-01 19:03:55,311] - ==> [2019-03-01 19:03:55 307] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00002334] [2019-03-01 19:03:55,348] - TCPPacketReceiver::processPendingEvents(192.168.0.148:9657): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002334] [2019-03-01 19:03:55,348] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00002334] [2019-03-01 19:03:55,348] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002334] [2019-03-01 19:03:55,358] - onBaseAppShutDown: state=0
  INFO root [0x00002334] [2019-03-01 19:03:55,358] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002334] [2019-03-01 19:03:55,358] - onBaseAppShutDown: state=1
  INFO root [0x00002334] [2019-03-01 19:03:55,358] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002334] [2019-03-01 19:03:55,358] - onBaseAppShutDown: state=2
 ERROR root [0x00002334] [2019-03-01 19:03:55,371] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00002334] [2019-03-01 19:03:55,371] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002334] [2019-03-01 19:03:55,371] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00002334] [2019-03-01 19:03:55,378] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002334] [2019-03-01 19:03:55,378] - Account::~Account(): 2
 DEBUG root [0x00002334] [2019-03-01 19:03:55,378] - Halls::~Halls(): 1
 DEBUG root [0x00002334] [2019-03-01 19:03:55,378] - Account::~Account(): 4
 DEBUG root [0x00002334] [2019-03-01 19:03:55,378] - Room::~Room(): 3
  INFO root [0x00002334] [2019-03-01 19:03:55,388] - Script::uninstall(): is successfully!
 DEBUG root [0x00002334] [2019-03-01 19:03:55,388] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000038fc] [2019-03-01 19:04:54,701] - 
  INFO root [0x000038fc] [2019-03-01 19:04:54,703] - -----------------------------------------------------------------------------------------


  INFO root [0x000038fc] [2019-03-01 19:04:54,704] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x000038fc] [2019-03-01 19:04:54,705] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x000038fc] [2019-03-01 19:04:54,705] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x000038fc] [2019-03-01 19:04:54,720] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x000038fc] [2019-03-01 19:04:54,720] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x000038fc] [2019-03-01 19:04:54,723] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x000038fc] [2019-03-01 19:04:54,724] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x000038fc] [2019-03-01 19:04:54,727] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10896 )
  INFO root [0x000038fc] [2019-03-01 19:04:54,727] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10896, SOMAXCONN=128.
  INFO root [0x000038fc] [2019-03-01 19:04:54,727] - server-configs:
  INFO root [0x000038fc] [2019-03-01 19:04:54,728] - 	gameUpdateHertz : 10
  INFO root [0x000038fc] [2019-03-01 19:04:54,729] - 	entryScriptFile : kbemain
  INFO root [0x000038fc] [2019-03-01 19:04:54,729] - 	internalTcpAddr : 192.168.0.148:10896
  INFO root [0x000038fc] [2019-03-01 19:04:54,729] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x000038fc] [2019-03-01 19:04:54,729] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x000038fc] [2019-03-01 19:04:54,729] - 	componentID : 7001
  WARN root [0x000038fc] [2019-03-01 19:04:55,118] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x000038fc] [2019-03-01 19:04:55,268] - Components::findLogger: found logger, addr:192.168.0.148:10892
  INFO root [0x000038fc] [2019-03-01 19:04:55,268] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000038fc] [2019-03-01 19:04:55,268] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000038fc] [2019-03-01 19:04:55,278] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 2728 ----
  INFO root [0x000038fc] [2019-03-01 19:04:55,278] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x000038fc] [2019-03-01 19:04:55,278] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000038fc] [2019-03-01 19:04:55,278] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000038fc] [2019-03-01 19:04:55,458] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000038fc] [2019-03-01 19:04:55,458] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000038fc] [2019-03-01 19:04:55,552] - loaded entity-script:Account(1).
 DEBUG root [0x000038fc] [2019-03-01 19:04:55,553] - loaded entity-script:Halls(2).
 DEBUG root [0x000038fc] [2019-03-01 19:04:55,553] - loaded entity-script:Room(3).
  INFO root [0x000038fc] [2019-03-01 19:04:55,553] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000038fc] [2019-03-01 19:04:55,554] - TelnetServer server is running on port 40000
  INFO root [0x000038fc] [2019-03-01 19:04:55,931] - ---- baseapp is running ----
 DEBUG root [0x000038fc] [2019-03-01 19:04:55,931] - Components::process(): Request for the process of identity...
  WARN root [0x000038fc] [2019-03-01 19:04:59,478] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20224, errorno=10048
  WARN root [0x000038fc] [2019-03-01 19:05:02,588] - Forwarding logs to logger[192.168.0.148:10892/0/0/0]...
  INFO root [0x00001928] [2019-03-01 19:06:00,622] - 
  INFO root [0x00001928] [2019-03-01 19:06:00,623] - -----------------------------------------------------------------------------------------


  INFO root [0x00001928] [2019-03-01 19:06:00,625] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00001928] [2019-03-01 19:06:00,625] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00001928] [2019-03-01 19:06:00,625] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00001928] [2019-03-01 19:06:00,630] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00001928] [2019-03-01 19:06:00,631] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00001928] [2019-03-01 19:06:00,634] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00001928] [2019-03-01 19:06:00,635] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00001928] [2019-03-01 19:06:00,638] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10979 )
  INFO root [0x00001928] [2019-03-01 19:06:00,639] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10979, SOMAXCONN=128.
  INFO root [0x00001928] [2019-03-01 19:06:00,639] - server-configs:
  INFO root [0x00001928] [2019-03-01 19:06:00,639] - 	gameUpdateHertz : 10
  INFO root [0x00001928] [2019-03-01 19:06:00,639] - 	entryScriptFile : kbemain
  INFO root [0x00001928] [2019-03-01 19:06:00,639] - 	internalTcpAddr : 192.168.0.148:10979
  INFO root [0x00001928] [2019-03-01 19:06:00,640] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00001928] [2019-03-01 19:06:00,640] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00001928] [2019-03-01 19:06:00,640] - 	componentID : 7001
  WARN root [0x00001928] [2019-03-01 19:06:00,974] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00001928] [2019-03-01 19:06:01,162] - Components::findLogger: found logger, addr:192.168.0.148:10982
  INFO root [0x00001928] [2019-03-01 19:06:01,162] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001928] [2019-03-01 19:06:01,162] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001928] [2019-03-01 19:06:01,168] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 6048 ----
  INFO root [0x00001928] [2019-03-01 19:06:01,168] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00001928] [2019-03-01 19:06:01,168] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001928] [2019-03-01 19:06:01,168] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001928] [2019-03-01 19:06:01,362] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001928] [2019-03-01 19:06:01,362] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001928] [2019-03-01 19:06:01,458] - loaded entity-script:Account(1).
 DEBUG root [0x00001928] [2019-03-01 19:06:01,458] - loaded entity-script:Halls(2).
 DEBUG root [0x00001928] [2019-03-01 19:06:01,458] - loaded entity-script:Room(3).
  INFO root [0x00001928] [2019-03-01 19:06:01,458] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001928] [2019-03-01 19:06:01,458] - TelnetServer server is running on port 40000
  INFO root [0x00001928] [2019-03-01 19:06:01,848] - ---- baseapp is running ----
 DEBUG root [0x00001928] [2019-03-01 19:06:01,848] - Components::process(): Request for the process of identity...
  WARN root [0x00001928] [2019-03-01 19:06:08,128] - Forwarding logs to logger[192.168.0.148:10982/0/0/0]...
 ERROR root [0x00001928] [2019-03-01 19:09:30,815] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001928] [2019-03-01 19:09:30,823] - The following logs sent to logger failed:
  WARN root [0x00001928] [2019-03-01 19:09:30,823] - ==> [2019-03-01 19:09:30 814] TCPPacketReceiver::processPendingEvents(192.168.0.148:10982): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001928] [2019-03-01 19:09:30,824] - ==> [2019-03-01 19:09:30 816] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00001928] [2019-03-01 19:09:30,860] - TCPPacketReceiver::processPendingEvents(192.168.0.148:10976): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001928] [2019-03-01 19:09:30,861] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001928] [2019-03-01 19:09:30,869] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001928] [2019-03-01 19:09:30,871] - onBaseAppShutDown: state=0
  INFO root [0x00001928] [2019-03-01 19:09:30,872] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001928] [2019-03-01 19:09:30,872] - onBaseAppShutDown: state=1
  INFO root [0x00001928] [2019-03-01 19:09:30,872] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001928] [2019-03-01 19:09:30,873] - onBaseAppShutDown: state=2
 ERROR root [0x00001928] [2019-03-01 19:09:30,887] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00001928] [2019-03-01 19:09:30,889] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001928] [2019-03-01 19:09:30,890] - Account::~Account(): 2
 DEBUG root [0x00001928] [2019-03-01 19:09:30,890] - Halls::~Halls(): 1
 DEBUG root [0x00001928] [2019-03-01 19:09:30,890] - Room::~Room(): 3
  INFO root [0x00001928] [2019-03-01 19:09:30,904] - Script::uninstall(): is successfully!
 DEBUG root [0x00001928] [2019-03-01 19:09:30,905] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003a0c] [2019-03-01 19:09:35,151] - 
  INFO root [0x00003a0c] [2019-03-01 19:09:35,155] - -----------------------------------------------------------------------------------------


  INFO root [0x00003a0c] [2019-03-01 19:09:35,157] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003a0c] [2019-03-01 19:09:35,157] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003a0c] [2019-03-01 19:09:35,158] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003a0c] [2019-03-01 19:09:35,163] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20015 )
  INFO root [0x00003a0c] [2019-03-01 19:09:35,164] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20015, SOMAXCONN=128.
  INFO root [0x00003a0c] [2019-03-01 19:09:35,167] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20005 )
  INFO root [0x00003a0c] [2019-03-01 19:09:35,167] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.0.148:20005, SOMAXCONN=128.
  INFO root [0x00003a0c] [2019-03-01 19:09:35,171] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:11078 )
  INFO root [0x00003a0c] [2019-03-01 19:09:35,172] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:11078, SOMAXCONN=128.
  INFO root [0x00003a0c] [2019-03-01 19:09:35,172] - server-configs:
  INFO root [0x00003a0c] [2019-03-01 19:09:35,172] - 	gameUpdateHertz : 10
  INFO root [0x00003a0c] [2019-03-01 19:09:35,173] - 	entryScriptFile : kbemain
  INFO root [0x00003a0c] [2019-03-01 19:09:35,173] - 	internalTcpAddr : 192.168.0.148:11078
  INFO root [0x00003a0c] [2019-03-01 19:09:35,173] - 	externalTcpAddr : 192.168.0.148:20015
  INFO root [0x00003a0c] [2019-03-01 19:09:35,173] - 	externalUdpAddr : 192.168.0.148:20005
  INFO root [0x00003a0c] [2019-03-01 19:09:35,173] - 	componentID : 7001
  WARN root [0x00003a0c] [2019-03-01 19:09:35,473] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003a0c] [2019-03-01 19:09:35,740] - Components::findLogger: found logger, addr:192.168.0.148:11082
  INFO root [0x00003a0c] [2019-03-01 19:09:35,741] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003a0c] [2019-03-01 19:09:35,741] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a0c] [2019-03-01 19:09:35,749] - ---- baseapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 18914A7099A0127BD73DD63149F1D9BA. Config: Debug X86. Built: 17:20:50 Feb 27 2019. AppID: 7001. UID: 28936. PID: 12572 ----
  INFO root [0x00003a0c] [2019-03-01 19:09:35,749] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003a0c] [2019-03-01 19:09:35,749] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003a0c] [2019-03-01 19:09:35,750] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003a0c] [2019-03-01 19:09:35,937] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003a0c] [2019-03-01 19:09:35,937] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003a0c] [2019-03-01 19:09:36,042] - loaded entity-script:Account(1).
 DEBUG root [0x00003a0c] [2019-03-01 19:09:36,043] - loaded entity-script:Halls(2).
 DEBUG root [0x00003a0c] [2019-03-01 19:09:36,043] - loaded entity-script:Room(3).
  INFO root [0x00003a0c] [2019-03-01 19:09:36,044] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003a0c] [2019-03-01 19:09:36,044] - TelnetServer server is running on port 40000
  INFO root [0x00003a0c] [2019-03-01 19:09:36,461] - ---- baseapp is running ----
 DEBUG root [0x00003a0c] [2019-03-01 19:09:36,461] - Components::process(): Request for the process of identity...
  WARN root [0x00003a0c] [2019-03-01 19:09:42,605] - Forwarding logs to logger[192.168.0.148:11082/0/0/0]...
 ERROR root [0x00003a0c] [2019-03-01 19:22:37,308] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

