  INFO root [2019-03-04 11:16:21,975] - 
  INFO root [2019-03-04 11:16:21,975] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-04 11:16:21,977] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-04 11:16:21,977] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-04 11:16:21,977] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-04 11:16:21,982] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10399 )
  INFO root [2019-03-04 11:16:21,982] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10399, SOMAXCONN=5.
  INFO root [2019-03-04 11:16:21,982] - server-configs:
  INFO root [2019-03-04 11:16:21,982] - 	internalTcpAddr : 192.168.0.148:10399
  INFO root [2019-03-04 11:16:21,982] - 	componentID : 4000
  WARN root [2019-03-04 11:16:21,985] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-04 11:16:22,052] - Components::findLogger: found logger, addr:192.168.0.148:10368
  INFO root [2019-03-04 11:16:22,053] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:16:22,053] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:16:22,057] - ---- dbmgr Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: C5660B1460B55E6E91E3FA119DC1798E. Config: Debug X86. Built: 17:19:55 Feb 27 2019. AppID: 4000. UID: 28936. PID: 13660 ----
  INFO root [2019-03-04 11:16:22,058] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-04 11:16:22,058] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-04 11:16:22,058] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-04 11:16:22,234] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-04 11:16:22,234] - Script::install(): KBExtra is successfully!
  INFO root [2019-03-04 11:16:22,334] - Dbmgr::initializeEnd: digest(4174ACFB13F6DB8EA9C92A0CF762CDAD)
S_INFO root [2019-03-04 11:16:22,334] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-04 11:16:22,335] - TelnetServer server is running on port 32000
  INFO root [2019-03-04 11:16:22,335] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2019-03-04 11:16:22,645] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
EA25B7B9D4C3EAABBDD5061D4F6C4AD445FC4EF67F79B5BEECC8CD6BB8E91A4FAE0BD24D4F43BA93B30FFE3AD075BA06BC771D6F48F4EFEC80520FA9747A033DB821E99B2B134388563C686B8AAF3D3C3C7C7430E8D674D59A948A974832E98DB080798308798EA79BDD7438A9F582DFC78347FB072C9F39FB18BE7943AAE44B
 DEBUG root [2019-03-04 11:16:22,654] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:16:22,764] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2019-03-04 11:16:22,764] - DBUtil::createInterface[0x39f3c8]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2019-03-04 11:16:22,764] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2019-03-04 11:16:22,765] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2019-03-04 11:16:22,765] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2019-03-04 11:16:22,765] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:16:22,765] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:16:22,766] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:16:22,766] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:16:22,794] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:16:22,795] - DBThread::onStart(): 0x9bd370!
 DEBUG root [2019-03-04 11:16:22,799] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:16:22,799] - DBThread::onStart(): 0x9bd040!
 DEBUG root [2019-03-04 11:16:22,803] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:16:22,803] - DBThread::onStart(): 0x9bd508!
 DEBUG root [2019-03-04 11:16:22,806] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:16:22,806] - DBThread::onStart(): 0x9bd0c8!
 DEBUG root [2019-03-04 11:16:22,809] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:16:22,809] - DBThread::onStart(): 0x9bd150!
  INFO root [2019-03-04 11:16:22,895] - DBInterfaceMysql::query: successfully!
  WARN root [2019-03-04 11:16:22,895] - DBInterfaceMysql::checkErrors: not found Account table(dbInterface=default), reset kbe_* table...
  WARN root [2019-03-04 11:16:22,922] - DBInterfaceMysql::checkErrors: reset kbe_* table(dbInterface=default) end!
  INFO root [2019-03-04 11:16:22,939] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:22,939] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:22,963] - DBInterfaceMysql::query: successfully!
 DEBUG root [2019-03-04 11:16:22,969] - syncToDB(): Account->sm_autoLoad(tinyint not null DEFAULT 0).
  INFO root [2019-03-04 11:16:22,976] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:22,978] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:22,979] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:22,979] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:16:23,005] - DBInterfaceMysql::query: successfully!
 DEBUG root [2019-03-04 11:16:23,006] - syncToDB(): Account->sm_roomKey(bigint unsigned not null DEFAULT 0).
  INFO root [2019-03-04 11:16:23,006] - DBInterfaceMysql::query: successfully!
 DEBUG root [2019-03-04 11:16:23,018] - syncToDB(): Account->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2019-03-04 11:16:23,033] - syncToDB(): Account->sm_0_position(float not null DEFAULT 0).
 DEBUG root [2019-03-04 11:16:23,064] - syncToDB(): Account->sm_1_position(float not null DEFAULT 0).
 DEBUG root [2019-03-04 11:16:23,080] - syncToDB(): Account->sm_2_position(float not null DEFAULT 0).
 DEBUG root [2019-03-04 11:16:23,094] - syncToDB(): Account->sm_0_direction(float not null DEFAULT 0).
 DEBUG root [2019-03-04 11:16:23,108] - syncToDB(): Account->sm_1_direction(float not null DEFAULT 0).
 DEBUG root [2019-03-04 11:16:23,124] - syncToDB(): Account->sm_2_direction(float not null DEFAULT 0).
  WARN root [2019-03-04 11:16:23,145] - DBTask::process(): took 0.22 seconds
sql:(show index from tbl_Account)
 DEBUG root [2019-03-04 11:16:23,168] - DBInterfaceMysql::dropEntityTableFromDB: tbl_avatar.
  INFO root [2019-03-04 11:16:23,180] - DBInterfaceMysql::query: successfully!
 DEBUG root [2019-03-04 11:16:23,180] - DBInterfaceMysql::dropEntityTableFromDB: tbl_food.
  INFO root [2019-03-04 11:16:23,194] - DBInterfaceMysql::query: successfully!
 DEBUG root [2019-03-04 11:16:23,194] - DBInterfaceMysql::dropEntityTableFromDB: tbl_smash.
  INFO root [2019-03-04 11:16:23,208] - DBInterfaceMysql::query: successfully!
  WARN root [2019-03-04 11:16:23,208] - d:\kbengine-2.4.2\kbe\src\server\dbmgr\dbmgr.cpp:304: Profile scriptCall took 0.87 seconds
  INFO root [2019-03-04 11:16:23,561] - ---- dbmgr is running ----
 DEBUG root [2019-03-04 11:16:23,561] - Components::process(): Request for the process of identity...
  WARN root [2019-03-04 11:16:29,789] - Forwarding logs to logger[192.168.0.148:10368/0/0/0]...
 ERROR root [2019-03-04 11:18:22,401] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-04 11:18:22,403] - The following logs sent to logger failed:
  WARN root [2019-03-04 11:18:22,403] - ==> [2019-03-04 11:18:22 400] TCPPacketReceiver::processPendingEvents(192.168.0.148:10368): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-04 11:18:22,404] - ==> [2019-03-04 11:18:22 401] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-04 11:18:25,190] - 
  INFO root [2019-03-04 11:18:25,193] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-04 11:18:25,195] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-04 11:18:25,195] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-04 11:18:25,195] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-04 11:18:25,205] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10724 )
  INFO root [2019-03-04 11:18:25,205] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10724, SOMAXCONN=5.
  INFO root [2019-03-04 11:18:25,205] - server-configs:
  INFO root [2019-03-04 11:18:25,205] - 	internalTcpAddr : 192.168.0.148:10724
  INFO root [2019-03-04 11:18:25,205] - 	componentID : 4000
  WARN root [2019-03-04 11:18:25,209] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [2019-03-04 11:18:25,639] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20707, errorno=10048
  INFO root [2019-03-04 11:18:25,645] - ---- dbmgr Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: C5660B1460B55E6E91E3FA119DC1798E. Config: Debug X86. Built: 17:19:55 Feb 27 2019. AppID: 4000. UID: 28936. PID: 7052 ----
  INFO root [2019-03-04 11:18:25,645] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-04 11:18:25,646] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-04 11:18:25,646] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-04 11:18:25,839] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-04 11:18:25,839] - Script::install(): KBExtra is successfully!
  INFO root [2019-03-04 11:18:25,864] - Dbmgr::initializeEnd: digest(4174ACFB13F6DB8EA9C92A0CF762CDAD)
S_INFO root [2019-03-04 11:18:25,864] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-04 11:18:25,865] - TelnetServer server is running on port 32000
  INFO root [2019-03-04 11:18:25,865] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2019-03-04 11:18:26,267] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
3EEB269479A0739EBD6B2F953A939EF00656440AA983467D97F315F5DC2FEA02432FE3857CFE9B40B339CAF9213EDAC2CABFE8B064C3C800143EB294BF90B102BCAD47CD9293271BA5749827D1C385893CF048EE765A1C08D947F4740F48B660287AAD631521F71A8A349E2900D1FB47DF972F17EF42561DF66D672B5902981B
 DEBUG root [2019-03-04 11:18:26,271] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:18:26,292] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2019-03-04 11:18:26,292] - DBUtil::createInterface[0xafefdc]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2019-03-04 11:18:26,292] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2019-03-04 11:18:26,292] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2019-03-04 11:18:26,293] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2019-03-04 11:18:26,293] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:18:26,293] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:18:26,293] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:18:26,293] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:18:26,325] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:18:26,325] - DBThread::onStart(): 0x12d9d0!
 DEBUG root [2019-03-04 11:18:26,328] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:18:26,329] - DBThread::onStart(): 0x12d480!
 DEBUG root [2019-03-04 11:18:26,332] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:18:26,333] - DBThread::onStart(): 0x12d7b0!
 DEBUG root [2019-03-04 11:18:26,335] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:18:26,336] - DBThread::onStart(): 0x12d508!
 DEBUG root [2019-03-04 11:18:26,338] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:18:26,338] - DBThread::onStart(): 0x12cc88!
  INFO root [2019-03-04 11:18:26,411] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,414] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,414] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,414] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,415] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,416] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,417] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,417] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:18:26,426] - DBInterfaceMysql::query: successfully!
  WARN root [2019-03-04 11:18:26,456] - d:\kbengine-2.4.2\kbe\src\server\dbmgr\dbmgr.cpp:304: Profile scriptCall took 0.59 seconds
  INFO root [2019-03-04 11:18:26,778] - ---- dbmgr is running ----
 DEBUG root [2019-03-04 11:18:26,779] - Components::process(): Request for the process of identity...
  INFO root [2019-03-04 11:18:32,903] - ServerApp::onRegisterNewApp: uid:28936, username:19, componentType:interfaces, componentID:3000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.148, intport:30099, extaddr:nonsupport, extport:0,  from 127.0.0.1:30099/0/0/0.
  INFO root [2019-03-04 11:18:32,904] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:18:32,904] - Components::addComponent[interfaces], uid=28936, componentID=3000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:18:33,925] - Components::findComponents: find logger(1)...
  INFO root [2019-03-04 11:18:33,934] - Components::findComponents: found logger, addr:192.168.0.148:10723
  INFO root [2019-03-04 11:18:33,934] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:18:33,934] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:18:33,944] - Components::process(): Found all the components!
  WARN root [2019-03-04 11:18:33,999] - Forwarding logs to logger[192.168.0.148:10723/0/0/0]...
  INFO root [2019-03-04 11:19:40,430] - 
  INFO root [2019-03-04 11:19:40,431] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-04 11:19:40,432] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-04 11:19:40,432] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-04 11:19:40,432] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-04 11:19:40,437] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10929 )
  INFO root [2019-03-04 11:19:40,438] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10929, SOMAXCONN=5.
  INFO root [2019-03-04 11:19:40,438] - server-configs:
  INFO root [2019-03-04 11:19:40,438] - 	internalTcpAddr : 192.168.0.148:10929
  INFO root [2019-03-04 11:19:40,438] - 	componentID : 4000
  WARN root [2019-03-04 11:19:40,442] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-04 11:19:41,951] - ---- dbmgr Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: C5660B1460B55E6E91E3FA119DC1798E. Config: Debug X86. Built: 17:19:55 Feb 27 2019. AppID: 4000. UID: 28936. PID: 5432 ----
  INFO root [2019-03-04 11:19:41,951] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-04 11:19:41,952] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-04 11:19:41,952] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-04 11:19:42,121] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-04 11:19:42,121] - Script::install(): KBExtra is successfully!
  INFO root [2019-03-04 11:19:42,141] - Dbmgr::initializeEnd: digest(4174ACFB13F6DB8EA9C92A0CF762CDAD)
S_INFO root [2019-03-04 11:19:42,141] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-04 11:19:42,142] - TelnetServer server is running on port 32000
  INFO root [2019-03-04 11:19:42,142] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2019-03-04 11:19:42,472] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
09C95A179E3013CD9E6DDCCB80501AA23183CD2D1A492FE79C8B23D4D2F57855C59256FEEDDD66F089E551F9A6A24F7FC2C41104726A2100569C0311E34B037774ACEE8678FA4BDC2A421D236217B8E72AA45210C0FE388B69157935C8962C569375BA73FC881C51430E9CEA14C1B7ADC8065F0AAE03584075DA6A132D49F49B
 DEBUG root [2019-03-04 11:19:42,476] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,500] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2019-03-04 11:19:42,500] - DBUtil::createInterface[0x9dedb0]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2019-03-04 11:19:42,500] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-04 11:19:42,501] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2019-03-04 11:19:42,501] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,502] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,502] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,502] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,503] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:19:42,534] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:19:42,534] - DBThread::onStart(): 0x27f288!
 DEBUG root [2019-03-04 11:19:42,538] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:19:42,538] - DBThread::onStart(): 0x27f6c8!
 DEBUG root [2019-03-04 11:19:42,541] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:19:42,541] - DBThread::onStart(): 0x27f398!
 DEBUG root [2019-03-04 11:19:42,544] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:19:42,544] - DBThread::onStart(): 0x27f970!
 DEBUG root [2019-03-04 11:19:42,547] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:19:42,547] - DBThread::onStart(): 0x27f9f8!
  INFO root [2019-03-04 11:19:42,616] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,620] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,620] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,620] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,621] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,621] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,621] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,622] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:19:42,626] - DBInterfaceMysql::query: successfully!
  WARN root [2019-03-04 11:19:42,647] - d:\kbengine-2.4.2\kbe\src\server\dbmgr\dbmgr.cpp:304: Profile scriptCall took 0.50 seconds
  INFO root [2019-03-04 11:19:42,980] - ---- dbmgr is running ----
 DEBUG root [2019-03-04 11:19:42,980] - Components::process(): Request for the process of identity...
  INFO root [2019-03-04 11:19:49,173] - ServerApp::onRegisterNewApp: uid:28936, username:19, componentType:interfaces, componentID:3000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.148, intport:30099, extaddr:nonsupport, extport:0,  from 127.0.0.1:30099/0/0/0.
  INFO root [2019-03-04 11:19:49,173] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:19:49,173] - Components::addComponent[interfaces], uid=28936, componentID=3000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:19:50,175] - Components::findComponents: find logger(1)...
  INFO root [2019-03-04 11:19:50,268] - Components::findComponents: found logger, addr:192.168.0.148:10931
  INFO root [2019-03-04 11:19:50,268] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:19:50,268] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  WARN root [2019-03-04 11:19:50,269] - Forwarding logs to logger[192.168.0.148:10931/0/0/0]...
 ERROR root [2019-03-04 11:24:19,735] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-04 11:24:19,738] - The following logs sent to logger failed:
  WARN root [2019-03-04 11:24:19,738] - ==> [2019-03-04 11:24:19 735] TCPPacketReceiver::processPendingEvents(192.168.0.148:10931): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-04 11:24:19,739] - ==> [2019-03-04 11:24:19 736] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-04 11:37:43,445] - 
  INFO root [2019-03-04 11:37:43,447] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-04 11:37:43,448] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-04 11:37:43,448] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-04 11:37:43,449] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-04 11:37:43,454] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:13427 )
  INFO root [2019-03-04 11:37:43,454] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:13427, SOMAXCONN=5.
  INFO root [2019-03-04 11:37:43,455] - server-configs:
  INFO root [2019-03-04 11:37:43,455] - 	internalTcpAddr : 192.168.0.148:13427
  INFO root [2019-03-04 11:37:43,455] - 	componentID : 4000
  WARN root [2019-03-04 11:37:43,459] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-04 11:37:44,969] - ---- dbmgr Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: C5660B1460B55E6E91E3FA119DC1798E. Config: Debug X86. Built: 17:19:55 Feb 27 2019. AppID: 4000. UID: 28936. PID: 12768 ----
  INFO root [2019-03-04 11:37:44,970] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-04 11:37:44,970] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-04 11:37:44,970] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-04 11:37:45,153] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-04 11:37:45,153] - Script::install(): KBExtra is successfully!
  INFO root [2019-03-04 11:37:45,172] - Dbmgr::initializeEnd: digest(4174ACFB13F6DB8EA9C92A0CF762CDAD)
S_INFO root [2019-03-04 11:37:45,173] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-04 11:37:45,173] - TelnetServer server is running on port 32000
  INFO root [2019-03-04 11:37:45,173] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2019-03-04 11:37:45,466] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
6D94565D09359479F0AE777D0DE31ED65C622F7F709539896F58FE4AB81BDB656B20E95C2C97DA63413C9385532E88F361E0C265323A3EC48D7A20C9B68674E026A57D475B6F2F70E112FDA7CF6FF5DC40BFE149B301216AC226CF6F4A4B07323C01F56E4201D95579AC44AFD715760A15B1BBEB4EB37FD1E058CE002F450A87
 DEBUG root [2019-03-04 11:37:45,470] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:37:45,511] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2019-03-04 11:37:45,511] - DBUtil::createInterface[0x58f184]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2019-03-04 11:37:45,511] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2019-03-04 11:37:45,512] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2019-03-04 11:37:45,512] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2019-03-04 11:37:45,512] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:37:45,512] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:37:45,513] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:37:45,513] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2019-03-04 11:37:45,539] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:37:45,540] - DBThread::onStart(): 0x7cb1b0!
 DEBUG root [2019-03-04 11:37:45,544] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:37:45,544] - DBThread::onStart(): 0x7caac8!
 DEBUG root [2019-03-04 11:37:45,547] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:37:45,547] - DBThread::onStart(): 0x7cb810!
 DEBUG root [2019-03-04 11:37:45,551] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:37:45,551] - DBThread::onStart(): 0x7cac60!
 DEBUG root [2019-03-04 11:37:45,554] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2019-03-04 11:37:45,554] - DBThread::onStart(): 0x7ca930!
  INFO root [2019-03-04 11:37:45,637] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,640] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,641] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,642] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,642] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,643] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,645] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,657] - DBInterfaceMysql::query: successfully!
  INFO root [2019-03-04 11:37:45,657] - DBInterfaceMysql::query: successfully!
  WARN root [2019-03-04 11:37:45,689] - d:\kbengine-2.4.2\kbe\src\server\dbmgr\dbmgr.cpp:304: Profile scriptCall took 0.52 seconds
  INFO root [2019-03-04 11:37:45,987] - ---- dbmgr is running ----
 DEBUG root [2019-03-04 11:37:45,987] - Components::process(): Request for the process of identity...
  INFO root [2019-03-04 11:37:52,190] - ServerApp::onRegisterNewApp: uid:28936, username:19, componentType:interfaces, componentID:3000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.148, intport:30099, extaddr:nonsupport, extport:0,  from 127.0.0.1:30099/0/0/0.
  INFO root [2019-03-04 11:37:52,191] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:37:52,191] - Components::addComponent[interfaces], uid=28936, componentID=3000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:37:53,194] - Components::findComponents: find logger(1)...
  INFO root [2019-03-04 11:37:53,228] - Components::findComponents: found logger, addr:192.168.0.148:13426
  INFO root [2019-03-04 11:37:53,228] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-04 11:37:53,228] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-04 11:37:53,256] - Components::process(): Found all the components!
  WARN root [2019-03-04 11:37:53,256] - Forwarding logs to logger[192.168.0.148:13426/0/0/0]...
 ERROR root [2019-03-04 12:58:16,065] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-04 12:58:16,069] - The following logs sent to logger failed:
  WARN root [2019-03-04 12:58:16,069] - ==> [2019-03-04 12:58:16 064] TCPPacketReceiver::processPendingEvents(192.168.0.148:13426): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-04 12:58:16,070] - ==> [2019-03-04 12:58:16 066] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

